#############################################################################
# Makefile for building: TradeCalculator
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  TradeCalculator.pro
# Template: app
# Command: /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake -o Makefile TradeCalculator.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DISABLE_DEPRECATED_BEFORE=0x050F00 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -ffunction-sections -fdata-sections -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -ffunction-sections -fdata-sections -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/vic/freestore/MySources/TradeCalculator/sources/lib/include -I../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include -I../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets -I../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui -I../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore -I. -I. -I../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/linux-g++
QMAKE         = /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TradeCalculator1.0.0
DISTDIR = /home/vic/freestore/MySources/TradeCalculator/sources/.tmp/TradeCalculator1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,--gc-sections
LIBS          = $(SUBLIBS) -L/home/vic/freestore/MySources/TradeCalculator/sources/lib/ -lmmcalc3 /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/plugins/styles/libqwindowsvistastyle.a /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/plugins/platforms/libqwindows.a /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/libqgif.a /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/libqico.a /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/libqjpeg.a /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5Widgets.a /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5Gui.a /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5Core.a -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		dialog.cpp /home/vic/freestore/MySources/TradeCalculator/sources/tradecalculator_plugin_import.cpp \
		moc_dialog.cpp
OBJECTS       = main.o \
		dialog.o \
		tradecalculator_plugin_import.o \
		moc_dialog.o
DIST          = ../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_pre.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/unix.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/linux.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/sanitize.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/gcc-base.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/gcc-base-unix.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/g++-base.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/g++-unix.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qconfig.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qdirect2d.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgif.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qico.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlmysql.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlpsql.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqltds.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindows.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_functions.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_config.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/linux-g++/qmake.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/toolchain.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_pre.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resolve_config.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_post.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/warn_on.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/gc_binaries.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resources_functions.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resources.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/moc.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/unix/opengl.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/uic.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/unix/thread.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qmake_use.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/file_copies.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/testcase_targets.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exceptions.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/yacc.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/lex.prf \
		TradeCalculator.pro dialog.h main.cpp \
		dialog.cpp
QMAKE_TARGET  = TradeCalculator
DESTDIR       = 
TARGET        = TradeCalculator


first: all
####### Build rules

TradeCalculator: /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5Widgets.a /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5Gui.a /home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5Core.a ui_TradeCalculator.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TradeCalculator.pro ../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/linux-g++/qmake.conf ../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_pre.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/unix.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/linux.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/sanitize.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/gcc-base.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/gcc-base-unix.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/g++-base.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/g++-unix.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qconfig.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qdirect2d.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgif.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qico.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlmysql.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlpsql.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqltds.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindows.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_functions.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_config.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/linux-g++/qmake.conf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/toolchain.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_pre.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resolve_config.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_post.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/warn_on.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/gc_binaries.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resources_functions.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resources.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/moc.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/unix/opengl.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/uic.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/unix/thread.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qmake_use.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/file_copies.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/testcase_targets.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exceptions.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/yacc.prf \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/lex.prf \
		TradeCalculator.pro
	$(QMAKE) -o Makefile TradeCalculator.pro -spec linux-g++
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_pre.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/unix.conf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/linux.conf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/sanitize.conf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/gcc-base.conf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/gcc-base-unix.conf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/g++-base.conf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/g++-unix.conf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qconfig.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qdirect2d.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgif.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qico.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjpeg.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qminimal.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlite.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlmysql.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlodbc.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlpsql.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqltds.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindows.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_functions.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_config.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/linux-g++/qmake.conf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_post.prf:
../.qmake.stash:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/toolchain.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_pre.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resolve_config.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_post.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/warn_on.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/gc_binaries.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resources_functions.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resources.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/moc.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/unix/opengl.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/uic.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/unix/thread.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qmake_use.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/file_copies.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/testcase_targets.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exceptions.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/yacc.prf:
../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/lex.prf:
TradeCalculator.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile TradeCalculator.pro -spec linux-g++

qmake_all: FORCE


all: Makefile TradeCalculator

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents dialog.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp dialog.cpp $(DISTDIR)/
	$(COPY_FILE) --parents TradeCalculator.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) /home/vic/freestore/MySources/TradeCalculator/sources/tradecalculator_plugin_import.cpp
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -ffunction-sections -fdata-sections -dM -E -o moc_predefs.h ../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp
moc_dialog.cpp: dialog.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QDialog \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qdialog.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qtwidgetsglobal.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtguiglobal.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qglobal.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qconfig-bootstrapped.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qconfig.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qtcore-config.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsystemdetection.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qprocessordetection.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcompilerdetection.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qtypeinfo.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsysinfo.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qlogging.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qflags.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qatomic.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qbasicatomic.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qatomic_bootstrap.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qgenericatomic.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qatomic_cxx11.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qatomic_msvc.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qglobalstatic.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qmutex.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qnumeric.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qversiontagging.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtgui-config.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qtwidgets-config.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qwidget.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qwindowdefs.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qobjectdefs.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qnamespace.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qobjectdefs_impl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qwindowdefs_win.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qobject.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstring.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qchar.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qbytearray.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qrefcount.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qarraydata.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringliteral.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringalgorithms.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringview.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringbuilder.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qlist.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qalgorithms.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qiterator.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qhashfunctions.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qpair.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qvector.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcontainertools_impl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qpoint.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qbytearraylist.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringlist.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qregexp.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringmatcher.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcoreevent.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qscopedpointer.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qmetatype.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qvarlengtharray.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcontainerfwd.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qobject_impl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qmargins.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpaintdevice.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qrect.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsize.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpalette.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qcolor.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qrgb.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qrgba64.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qbrush.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qmatrix.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpolygon.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qregion.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qdatastream.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qiodevice.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qline.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtransform.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qimage.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpixelformat.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpixmap.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsharedpointer.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qshareddata.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qhash.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsharedpointer_impl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qfont.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qfontmetrics.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qfontinfo.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qsizepolicy.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qcursor.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qkeysequence.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qevent.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qvariant.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qmap.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qdebug.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qtextstream.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qlocale.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qset.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcontiguouscache.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qurl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qurlquery.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qfile.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qfiledevice.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qvector2d.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtouchdevice.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QMessageBox \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qmessagebox.h \
		moc_predefs.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/bin/moc
	/home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/bin/moc $(DEFINES) --include /home/vic/freestore/MySources/TradeCalculator/sources/moc_predefs.h -I/home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/linux-g++ -I/home/vic/freestore/MySources/TradeCalculator/sources -I/home/vic/freestore/MySources/TradeCalculator/sources/lib/include -I/home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/include -I/home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets -I/home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui -I/home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore -I/usr/include/c++/11.1.0 -I/usr/include/c++/11.1.0/x86_64-pc-linux-gnu -I/usr/include/c++/11.1.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include-fixed -I/usr/include dialog.h -o moc_dialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_TradeCalculator.h
compiler_uic_clean:
	-$(DEL_FILE) ui_TradeCalculator.h
ui_TradeCalculator.h: TradeCalculator.ui \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/bin/uic
	/home/vic/programs/mxe/usr/i686-w64-mingw32.static/qt5/bin/uic TradeCalculator.ui -o ui_TradeCalculator.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp dialog.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QDialog \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qdialog.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qtwidgetsglobal.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtguiglobal.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qglobal.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qconfig-bootstrapped.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qconfig.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qtcore-config.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsystemdetection.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qprocessordetection.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcompilerdetection.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qtypeinfo.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsysinfo.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qlogging.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qflags.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qatomic.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qbasicatomic.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qatomic_bootstrap.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qgenericatomic.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qatomic_cxx11.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qatomic_msvc.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qglobalstatic.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qmutex.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qnumeric.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qversiontagging.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtgui-config.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qtwidgets-config.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qwidget.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qwindowdefs.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qobjectdefs.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qnamespace.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qobjectdefs_impl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qwindowdefs_win.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qobject.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstring.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qchar.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qbytearray.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qrefcount.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qarraydata.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringliteral.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringalgorithms.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringview.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringbuilder.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qlist.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qalgorithms.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qiterator.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qhashfunctions.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qpair.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qvector.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcontainertools_impl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qpoint.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qbytearraylist.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringlist.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qregexp.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringmatcher.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcoreevent.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qscopedpointer.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qmetatype.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qvarlengtharray.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcontainerfwd.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qobject_impl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qmargins.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpaintdevice.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qrect.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsize.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpalette.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qcolor.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qrgb.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qrgba64.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qbrush.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qmatrix.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpolygon.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qregion.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qdatastream.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qiodevice.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qline.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtransform.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qimage.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpixelformat.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpixmap.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsharedpointer.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qshareddata.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qhash.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsharedpointer_impl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qfont.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qfontmetrics.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qfontinfo.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qsizepolicy.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qcursor.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qkeysequence.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qevent.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qvariant.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qmap.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qdebug.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qtextstream.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qlocale.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qset.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcontiguouscache.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qurl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qurlquery.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qfile.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qfiledevice.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qvector2d.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtouchdevice.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QMessageBox \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qmessagebox.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QApplication \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qapplication.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcoreapplication.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qeventloop.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qdesktopwidget.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qguiapplication.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dialog.o: dialog.cpp dialog.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QDialog \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qdialog.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qtwidgetsglobal.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtguiglobal.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qglobal.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qconfig-bootstrapped.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qconfig.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qtcore-config.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsystemdetection.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qprocessordetection.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcompilerdetection.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qtypeinfo.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsysinfo.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qlogging.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qflags.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qatomic.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qbasicatomic.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qatomic_bootstrap.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qgenericatomic.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qatomic_cxx11.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qatomic_msvc.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qglobalstatic.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qmutex.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qnumeric.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qversiontagging.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtgui-config.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qtwidgets-config.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qwidget.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qwindowdefs.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qobjectdefs.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qnamespace.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qobjectdefs_impl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qwindowdefs_win.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qobject.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstring.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qchar.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qbytearray.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qrefcount.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qarraydata.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringliteral.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringalgorithms.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringview.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringbuilder.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qlist.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qalgorithms.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qiterator.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qhashfunctions.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qpair.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qvector.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcontainertools_impl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qpoint.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qbytearraylist.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringlist.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qregexp.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qstringmatcher.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcoreevent.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qscopedpointer.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qmetatype.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qvarlengtharray.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcontainerfwd.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qobject_impl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qmargins.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpaintdevice.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qrect.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsize.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpalette.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qcolor.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qrgb.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qrgba64.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qbrush.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qmatrix.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpolygon.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qregion.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qdatastream.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qiodevice.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qline.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtransform.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qimage.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpixelformat.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpixmap.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsharedpointer.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qshareddata.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qhash.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qsharedpointer_impl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qfont.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qfontmetrics.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qfontinfo.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qsizepolicy.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qcursor.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qkeysequence.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qevent.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qvariant.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qmap.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qdebug.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qtextstream.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qlocale.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qset.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcontiguouscache.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qurl.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qurlquery.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qfile.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qfiledevice.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qvector2d.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtouchdevice.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QMessageBox \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qmessagebox.h \
		ui_TradeCalculator.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/QVariant \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QApplication \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qapplication.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qcoreapplication.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qeventloop.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qdesktopwidget.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qguiapplication.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qinputmethod.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QHeaderView \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qheaderview.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qabstractitemview.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qabstractscrollarea.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qframe.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qabstractitemmodel.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qitemselectionmodel.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qabstractitemdelegate.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qstyleoption.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qabstractspinbox.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qvalidator.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore/qregularexpression.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qicon.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qslider.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qabstractslider.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qstyle.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qtabbar.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qtabwidget.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qrubberband.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QLabel \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qlabel.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QLineEdit \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qlineedit.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtextcursor.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtextformat.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qpen.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtextoption.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QPushButton \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qpushbutton.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qabstractbutton.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QScrollArea \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qscrollarea.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QStackedWidget \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qstackedwidget.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QTableWidget \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qtablewidget.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qtableview.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QTextBrowser \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qtextbrowser.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qtextedit.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui/qtextdocument.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QVBoxLayout \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qboxlayout.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qlayout.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qlayoutitem.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/qgridlayout.h \
		../../../../programs/mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets/QWidget \
		mmcalc3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

tradecalculator_plugin_import.o: /home/vic/freestore/MySources/TradeCalculator/sources/tradecalculator_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tradecalculator_plugin_import.o /home/vic/freestore/MySources/TradeCalculator/sources/tradecalculator_plugin_import.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

